on: [push, pull_request]

name: Test and Build

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
        go-version: [1.20.x]
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Verify versions
        run: go version

      - name: Cache build artifacts
        id: cache-go
        uses: actions/cache@v4
        with:
          path: |
            ~/go/pkg/mod
            ${{ env.GOROOT }}
          key: ${{ runner.os }}-go-${{ matrix.go-version }}

      - name: Install dependencies
        run: go get
        working-directory: ./crisp

      - name: Build code
        run: go build
        working-directory: ./crisp

      - name: Test code
        run: go test
        working-directory: ./crisp
